# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: "Setup Scanners"
description: "Setup all scanners required / supported by ORT."

inputs:
  askalono-version:
    description: "The version of Askalono to set up. Defaults to 'latest'. Use 'none' to disable."
    required: false
  licensee-version:
    description: "The version of Licensee to set up. Defaults to 'latest'. Use 'none' to disable."
    required: false
  scancode-version:
    description: "The version of ScanCode to set up. Defaults to 'latest'. Use 'none' to disable."
    required: false

runs:
  # https://docs.github.com/en/actions/concepts/workflows-and-actions/custom-actions#types-of-actions
  using: "composite"
  steps:
  - name: "Setup Askalono"
    if: ${{ inputs.askalono-version != 'none' }}
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsshell
    shell: "bash"
    env:
      ASKALONO_VERSION: ${{ inputs.askalono-version }}
    continue-on-error: true
    run: |
      if [ -z "$ASKALONO_VERSION" -o "$ASKALONO_VERSION" = "latest" ]; then
        ASKALONO_VERSION=$(curl -sI https://github.com/jpeddicord/askalono/releases/latest \
          | grep -i "location:" | sed "s,.*/tag/,," | tr -d "\r\n")
      fi

      if [ -z "$ASKALONO_VERSION" ]; then
        echo "::error::The Askalono version must not be empty."
        exit 1
      fi

      ASKALONO_HOME=$RUNNER_TOOL_CACHE/askalono/$ASKALONO_VERSION

      if [ ! -d "$ASKALONO_HOME" ]; then
        mkdir -p "$ASKALONO_HOME"
        echo "::notice::Setting up Askalono version $ASKALONO_VERSION in '$ASKALONO_HOME'..."

        curl -sLO https://github.com/jpeddicord/askalono/releases/download/$ASKALONO_VERSION/askalono-Linux.zip
        unzip askalono-Linux.zip -d "$ASKALONO_HOME"
        rm askalono-Linux.zip
      else
        echo "::notice::Askalono version $ASKALONO_VERSION was already set up in '$ASKALONO_HOME'."
      fi

      echo "$ASKALONO_HOME" >> "$GITHUB_PATH"
  - name: "Setup Licensee"
    if: ${{ inputs.licensee-version != 'none' }}
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsshell
    shell: "bash"
    env:
      LICENSEE_VERSION: ${{ inputs.licensee-version }}
    continue-on-error: true
    run: |
      if [ -z "$LICENSEE_VERSION" -o "$LICENSEE_VERSION" = "latest" ]; then
        sudo gem install licensee
      else
        sudo gem install licensee:$LICENSEE_VERSION
      fi
  - name: "Setup ScanCode"
    if: ${{ inputs.scancode-version != 'none' }}
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsshell
    shell: "bash"
    env:
      SCANCODE_VERSION: ${{ inputs.scancode-version }}
    continue-on-error: true
    run: |
      if [ -z "$SCANCODE_VERSION" -o "$SCANCODE_VERSION" = "latest" ]; then
        pipx install scancode-toolkit
      else
        pipx install scancode-toolkit==$SCANCODE_VERSION
      fi
